config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root "home#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    # ログインしているかつadminカラムがtrueの場合
    if user && user.admin?
      # rails_adminへのアクセスを許可
      can :access, :rails_admin
      can :manage, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/acquisition_result.rb
class AcquisitionResult < ApplicationRecord
  enum :command, {
    wear: 0
  }
  validates :command, uniqueness: { scope: :date }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/command_error_history.rb
$client = Slack::Web::Client.new

class CommandErrorHistory < ApplicationRecord
  after_commit :slack_notify, on: :create

  enum :command, {
    wear: 0
  }

  def slack_notify
    $client.chat_postMessage(
      channel: ENV["TRENDY_ANTENNA_CHANNEL"],
      text: "#{error_class}: #{message}"
    )
    if screen_shot
      decoded_data = Base64.decode64(screen_shot)
      ss_path = "#{Rails.root}/tmp/wear/decode_screen_shot.png"
      File.open(ss_path, 'wb') do |f|
        f.write(decoded_data)
      end
      $client.files_upload(
        channels: ENV["TRENDY_ANTENNA_CHANNEL"],
        file: Faraday::UploadIO.new(
          ss_path, 'image/png'
        ),
        filename: 'error_screen_shot.png',
      )
    end
  end
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :outfit_posters, dependent: :nullify
end

app/models/hairstyle.rb
class Hairstyle < ApplicationRecord
  has_many :outfit_posters, dependent: :nullify
end

app/models/outfit_detail.rb
class OutfitDetail < ApplicationRecord
  has_many :outfit_rankings, dependent: :delete_all
  belongs_to :outfit_poster
end

app/models/outfit_poster.rb
class OutfitPoster < ApplicationRecord
  has_many :outfit_details, dependent: :delete_all
  belongs_to :gender
  belongs_to :hairstyle, optional: true
end

app/models/outfit_ranking.rb
class OutfitRanking < ApplicationRecord
  belongs_to :outfit_detail
  belongs_to :ranking_type

  scope :with_outfit_detail_and_poster, -> {
    joins(outfit_detail: :outfit_poster)
  }
  scope :with_ranking_type, -> {
    joins(:ranking_type)
  }
end

app/models/ranking_type.rb
class RankingType < ApplicationRecord
  has_many :outfit_rankings, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
require "date"
require "custom_formatter"

$logger = Logger.new("log/controller.log")
$logger.formatter = CustomFormatter.new

class HomeController < ApplicationController
  def index
    today = Date.today
    @men_rankings = OutfitRanking.with_outfit_detail_and_poster.with_ranking_type.where(
      ranking_type: {
        name: "men"
      }
    ).where(
      year: 2022,
      month: 6
    )
    @women_rankings = OutfitRanking.with_outfit_detail_and_poster.with_ranking_type.where(
      ranking_type: {
        name: "women"
      }
    ).where(
      year: 2022,
      month: 6
    )
    @kids_rankings = OutfitRanking.with_outfit_detail_and_poster.with_ranking_type.where(
      ranking_type: {
        name: "kids"
      }
    ).where(
      year: 2022,
      month: 6
    )
    if Rails.env.development?
      msg = "#{QueryDiet::Logger.count} queries / #{QueryDiet::Logger.time} ms"
      $logger.debug(msg)
      $logger.debug(@men_rankings.inspect.to_yaml)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <% if user_signed_in? %>
            <% if current_user.try(:admin?) %>
              <%= link_to rails_admin_path do %>
                <button type="button" class="btn btn-outline-light me-2">Admin</button>
              <% end %>
            <% end %>
            <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-warning" %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <button type="button" class="btn btn-outline-light me-2">Login</button>
            <% end %>
            <%= link_to new_user_registration_path do %>
              <button type="button" class="btn btn-warning">Sign-up</button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </header>

  <div class="container px-4 py-5" id="custom-cards">
    <h2 class="pb-2 border-bottom">MEN RANKING</h2>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      <% @men_rankings.each do |ranking| %>
        <div class="col">
          <div
            class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
          >
            <img src="<%= ranking.outfit_detail.img_url %>" class="img-responsive">
            <div class="d-flex flex-column p-5 text-white text-shadow-1">
              <div class="mb-4 display-6 fw-bold bg-dark rank"><%= ranking.rank %></div>
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <img src="<%= ranking.outfit_detail.outfit_poster.icon_url %>" alt="<%= ranking.outfit_detail.title %>" width="32" height="32" class="rounded-circle border border-white">
                </li>
                <li class="d-flex align-items-center me-3">
                  <a href="https://wear.jp/<%= ranking.outfit_detail.outfit_poster.user_id %>/" class="card-link"><%= ranking.outfit_detail.outfit_poster.name %></a>
                </li>
                <li class="d-flex align-items-center">
                  <a href="https://wear.jp/<%= ranking.outfit_detail.outfit_poster.user_id %>/<%= ranking.outfit_detail.fashion_id %>/" class="card-link">コーデ詳細</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <h2 class="pb-2 border-bottom">WOMEN RANKING</h2>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      <% @women_rankings.each do |ranking| %>
        <div class="col">
          <div
            class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
          >
            <img src="<%= ranking.outfit_detail.img_url %>" class="img-responsive">
            <div class="d-flex flex-column p-5 text-white text-shadow-1">
              <div class="mb-4 display-6 fw-bold bg-dark rank"><%= ranking.rank %></div>
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <img src="<%= ranking.outfit_detail.outfit_poster.icon_url %>" alt="<%= ranking.outfit_detail.title %>" width="32" height="32" class="rounded-circle border border-white">
                </li>
                <li class="d-flex align-items-center me-3">
                  <a href="https://wear.jp/<%= ranking.outfit_detail.outfit_poster.user_id %>/" class="card-link"><%= ranking.outfit_detail.outfit_poster.name %></a>
                </li>
                <li class="d-flex align-items-center">
                  <a href="https://wear.jp/<%= ranking.outfit_detail.outfit_poster.user_id %>/<%= ranking.outfit_detail.fashion_id %>/" class="card-link">コーデ詳細</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <h2 class="pb-2 border-bottom">KIDS RANKING</h2>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      <% @kids_rankings.each do |ranking| %>
        <div class="col">
          <div
            class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
          >
            <img src="<%= ranking.outfit_detail.img_url %>" class="img-responsive">
            <div class="d-flex flex-column p-5 text-white text-shadow-1">
              <div class="mb-4 display-6 fw-bold bg-dark rank"><%= ranking.rank %></div>
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <img src="<%= ranking.outfit_detail.outfit_poster.icon_url %>" alt="<%= ranking.outfit_detail.title %>" width="32" height="32" class="rounded-circle border border-white">
                </li>
                <li class="d-flex align-items-center me-3">
                  <a href="https://wear.jp/<%= ranking.outfit_detail.outfit_poster.user_id %>/" class="card-link"><%= ranking.outfit_detail.outfit_poster.name %></a>
                </li>
                <li class="d-flex align-items-center">
                  <a href="https://wear.jp/<%= ranking.outfit_detail.outfit_poster.user_id %>/<%= ranking.outfit_detail.fashion_id %>/" class="card-link">コーデ詳細</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrendyAntenna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>